### ISSUE TITLE
Best way to save a model/agent?

### ISSUE THREAD

**Issue by asmith26** [microsoft/coax#2]
Suppose I train a Q-Learning agent on FrozenLake as per [this tutorial](https://coax.readthedocs.io/en/latest/examples/getting_started/first_agent.html), what is the best way to save this model/agent for use elsewhere?

I'm thinking I need to just save the _Q_-values and the potentially the policy _pi_? Interestingly the doc seems to have a [`Q.save(...)`](https://coax.readthedocs.io/en/latest/coax/value_functions.html?highlight=load#coax.Q.save) and a [`pi.save(...)`](https://coax.readthedocs.io/en/latest/coax/policies.html?highlight=save#coax.Policy.save), however when I try to use them they appear to be possibly not currently implemented in the code? 

Many thanks for any help, and for this fantastic lib! :)

**Comment by KristianHolsheimer** [comment]
Thanks for your interest in coax!

By default, the readthedocs pages point to the [latest](https://coax.readthedocs.io/en/latest/) version of the code, which is the `main` branch here on github. The pypi version (from `pip install coax`) is the [stable](https://coax.readthedocs.io/en/stable/) version.

For now, there are two ways to solve this:

**Option 1** - Get the latest version by installing from a fresh clone:
```
git clone https://github.com/microsoft/coax.git
pip uninstall coax
pip install -e ./coax
```

**Option 2** - Pickle the objects yourself (requirements: `pip install lz4 cloudpickle`):
```python
import lz4.frame
import cloudpickle as pickle

# save
with lz4.frame.open(filepath, 'wb') as f:
    f.write(pickle.dumps((q, pi, ...)))

# load
with lz4.frame.open(filepath, 'rb') as f:
    q, pi, ... = pickle.loads(f.read())
```
This is how we're serializing objects in [SerializationMixin](https://github.com/microsoft/coax/blob/main/coax/_base/mixins/_serialization.py).

---
By the way, the reason why I haven't bumped the version yet is that I had some issues with serialization. So if you do run into issues, please let me know!

**Comment by asmith26** [comment]
Thanks very much for the fast response and your help!

Can confirm option 1 has allowed me to save `q` to disk (FYI trying `pi.save("model/pi")` yielded: `AttributeError: 'BoltzmannPolicy' object has no attribute 'save'`, nonetheless I can create a new `pi` using `q` which works fine).

Many thanks again!

**Comment by KristianHolsheimer** [comment]
FYI, I ended up dropping the save/load methods and added serialization utililty functions instead:
- [`coax.utils.dump`](https://coax.readthedocs.io/en/latest/coax/utils.html#coax.utils.dump)
- [`coax.utils.dumps`](https://coax.readthedocs.io/en/latest/coax/utils.html#coax.utils.dumps)
- [`coax.utils.load`](https://coax.readthedocs.io/en/latest/coax/utils.html#coax.utils.load)
- [`coax.utils.loads`](https://coax.readthedocs.io/en/latest/coax/utils.html#coax.utils.loads)

To ensure that all the relative object references are preserved when you serialize objects, it's safest to store everything together as a single object, e.g.
```python
q = coax.Q(func, env)
pi = coax.EpsilonGreedy(q, epsilon=0.1)
qlearning = coax.td_learning.QLearning(q)

# save
coax.utils.dump((q, pi, qlearning), 'checkpoint.pkl.lz4')

# load
q, pi, qlearning = coax.utils.load('checkpoint.pkl.lz4')
```
That way, `pi.q` and `qlearning.q` are still references to the same `q`.

**Comment by asmith26** [comment]
Makes sense to me, thanks for letting me know and for providing an example usage.
