### ISSUE TITLE
Parallelizing environments with coax?

### ISSUE THREAD

**Issue by jfpettit** [microsoft/coax#3]
Hi there,

Great library! Thanks a ton for doing this work.

I'm working on some environments that require a *lot* of samples and so was reading through the documentation looking for some sort of built-in way to handle running multiple environments in parallel. I didn't find anything, so I'm wondering, is there a utility I'm missing or perhaps a recommended way to handle this with coax? 

If not, are there plans to add support for parallel environments in the future?

Thanks again, so far coax is a delight to use!

**Comment by KristianHolsheimer** [comment]
Thanks for your interest in coax!

I'm currently working on support for distributed episode rollouts and distributed replay buffers. Unfortunately, it's not in a stable state at the moment.

I'll definitely keep you posted once that's out.

For the time being, you could try parallelizing it yourself. I made sure that everything is picklable, so multiprocessing / mpi / ray should work without too much headache.

If you want to get/set the state of a function approximator, just set/get the `params` and `function_state` properties.

I was trying out ray (without rllib!), see [`krholshe/apex`](https://github.com/microsoft/coax/tree/krholshe/apex) branch if you're interested. The code runs, but the agent isn't learning. I'll let you know when I finish debugging. Also, I'm not very happy with [`coax.Agent`](https://github.com/microsoft/coax/blob/krholshe/apex/coax/_core/agent.py#L199), I'll definitely need to clean that up.

**Comment by jfpettit** [comment]
Awesome! Thanks so much for getting back to me quickly! I'll certainly check out that branch. 

Do issues happen with ray + rllib?

I've been using rllib for benchmarking purposes and so my custom environments inherit from their [`MultiAgentEnv`](https://github.com/ray-project/ray/blob/master/rllib/env/multi_agent_env.py) class. I was having some weird issues trying to get coax to run in my environments before but have since resolved it, so I'm curious if you know whether I should expect more problems using rllib.

**Comment by KristianHolsheimer** [comment]
No I don't anticipate any issues with RLlib. I'm just not a huge fan of their fire-and-forget style.. I find it hard to know what's going.

Having said that, I have implemented coax-based custom RLlib Policies in the past without too much hassle.

Actually, yes there was an issue I had back then. JAX on GPU in a ray.remote process had some issues with running out of memory iirc. I believe it wasn't setting the `XLA_PYTHON_CLIENT_MEM_FRACTION` environment variable.

**Comment by jfpettit** [comment]
Sorry for the delay in response.

Happy New year to you! Thank you for getting back to me about my questions. I've got `coax` running and am now able to experiment with it. I'm gonna close this issue if that's OK!
